/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppEvaluationIndexImport } from './routes/_app/evaluation/index'
import { Route as AppEvaluationReportManagementIndexImport } from './routes/_app/evaluation/reportManagement/index'

// Create Virtual Routes

const AppIndexLazyImport = createFileRoute('/_app/')()
const AppNodeOperatorIndexLazyImport = createFileRoute('/_app/nodeOperator/')()
const AppLawyerWorkbenchIndexLazyImport = createFileRoute(
  '/_app/lawyerWorkbench/',
)()
const AppAsseteIndexLazyImport = createFileRoute('/_app/assete/')()
const AppAsseteAddAsseteIndexLazyImport = createFileRoute(
  '/_app/assete/addAssete/',
)()
const AppLawyerWorkbenchOfflineExecutionIdLazyImport = createFileRoute(
  '/_app/lawyerWorkbench/offlineExecution/$id',
)()
const AppLawyerWorkbenchInitialReviewIdLazyImport = createFileRoute(
  '/_app/lawyerWorkbench/initialReview/$id',
)()
const AppEvaluationInfoIdLazyImport = createFileRoute(
  '/_app/evaluation/info/$id',
)()
const AppAsseteInfoIdLazyImport = createFileRoute('/_app/assete/info/$id')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppNodeOperatorIndexLazyRoute = AppNodeOperatorIndexLazyImport.update({
  id: '/nodeOperator/',
  path: '/nodeOperator/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/nodeOperator/index.lazy').then((d) => d.Route),
)

const AppLawyerWorkbenchIndexLazyRoute =
  AppLawyerWorkbenchIndexLazyImport.update({
    id: '/lawyerWorkbench/',
    path: '/lawyerWorkbench/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/lawyerWorkbench/index.lazy').then((d) => d.Route),
  )

const AppAsseteIndexLazyRoute = AppAsseteIndexLazyImport.update({
  id: '/assete/',
  path: '/assete/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/assete/index.lazy').then((d) => d.Route),
)

const AppEvaluationIndexRoute = AppEvaluationIndexImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => AppRoute,
} as any)

const AppAsseteAddAsseteIndexLazyRoute =
  AppAsseteAddAsseteIndexLazyImport.update({
    id: '/assete/addAssete/',
    path: '/assete/addAssete/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/assete/addAssete/index.lazy').then((d) => d.Route),
  )

const AppEvaluationReportManagementIndexRoute =
  AppEvaluationReportManagementIndexImport.update({
    id: '/evaluation/reportManagement/',
    path: '/evaluation/reportManagement/',
    getParentRoute: () => AppRoute,
  } as any)

const AppLawyerWorkbenchOfflineExecutionIdLazyRoute =
  AppLawyerWorkbenchOfflineExecutionIdLazyImport.update({
    id: '/lawyerWorkbench/offlineExecution/$id',
    path: '/lawyerWorkbench/offlineExecution/$id',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/lawyerWorkbench/offlineExecution/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AppLawyerWorkbenchInitialReviewIdLazyRoute =
  AppLawyerWorkbenchInitialReviewIdLazyImport.update({
    id: '/lawyerWorkbench/initialReview/$id',
    path: '/lawyerWorkbench/initialReview/$id',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/lawyerWorkbench/initialReview/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AppEvaluationInfoIdLazyRoute = AppEvaluationInfoIdLazyImport.update({
  id: '/evaluation/info/$id',
  path: '/evaluation/info/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/evaluation/info/$id.lazy').then((d) => d.Route),
)

const AppAsseteInfoIdLazyRoute = AppAsseteInfoIdLazyImport.update({
  id: '/assete/info/$id',
  path: '/assete/info/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/assete/info/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/evaluation/': {
      id: '/_app/evaluation/'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof AppEvaluationIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/': {
      id: '/_app/assete/'
      path: '/assete'
      fullPath: '/assete'
      preLoaderRoute: typeof AppAsseteIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/lawyerWorkbench/': {
      id: '/_app/lawyerWorkbench/'
      path: '/lawyerWorkbench'
      fullPath: '/lawyerWorkbench'
      preLoaderRoute: typeof AppLawyerWorkbenchIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/nodeOperator/': {
      id: '/_app/nodeOperator/'
      path: '/nodeOperator'
      fullPath: '/nodeOperator'
      preLoaderRoute: typeof AppNodeOperatorIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/info/$id': {
      id: '/_app/assete/info/$id'
      path: '/assete/info/$id'
      fullPath: '/assete/info/$id'
      preLoaderRoute: typeof AppAsseteInfoIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/evaluation/info/$id': {
      id: '/_app/evaluation/info/$id'
      path: '/evaluation/info/$id'
      fullPath: '/evaluation/info/$id'
      preLoaderRoute: typeof AppEvaluationInfoIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/lawyerWorkbench/initialReview/$id': {
      id: '/_app/lawyerWorkbench/initialReview/$id'
      path: '/lawyerWorkbench/initialReview/$id'
      fullPath: '/lawyerWorkbench/initialReview/$id'
      preLoaderRoute: typeof AppLawyerWorkbenchInitialReviewIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/lawyerWorkbench/offlineExecution/$id': {
      id: '/_app/lawyerWorkbench/offlineExecution/$id'
      path: '/lawyerWorkbench/offlineExecution/$id'
      fullPath: '/lawyerWorkbench/offlineExecution/$id'
      preLoaderRoute: typeof AppLawyerWorkbenchOfflineExecutionIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/evaluation/reportManagement/': {
      id: '/_app/evaluation/reportManagement/'
      path: '/evaluation/reportManagement'
      fullPath: '/evaluation/reportManagement'
      preLoaderRoute: typeof AppEvaluationReportManagementIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/addAssete/': {
      id: '/_app/assete/addAssete/'
      path: '/assete/addAssete'
      fullPath: '/assete/addAssete'
      preLoaderRoute: typeof AppAsseteAddAsseteIndexLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppEvaluationIndexRoute: typeof AppEvaluationIndexRoute
  AppAsseteIndexLazyRoute: typeof AppAsseteIndexLazyRoute
  AppLawyerWorkbenchIndexLazyRoute: typeof AppLawyerWorkbenchIndexLazyRoute
  AppNodeOperatorIndexLazyRoute: typeof AppNodeOperatorIndexLazyRoute
  AppAsseteInfoIdLazyRoute: typeof AppAsseteInfoIdLazyRoute
  AppEvaluationInfoIdLazyRoute: typeof AppEvaluationInfoIdLazyRoute
  AppLawyerWorkbenchInitialReviewIdLazyRoute: typeof AppLawyerWorkbenchInitialReviewIdLazyRoute
  AppLawyerWorkbenchOfflineExecutionIdLazyRoute: typeof AppLawyerWorkbenchOfflineExecutionIdLazyRoute
  AppEvaluationReportManagementIndexRoute: typeof AppEvaluationReportManagementIndexRoute
  AppAsseteAddAsseteIndexLazyRoute: typeof AppAsseteAddAsseteIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppEvaluationIndexRoute: AppEvaluationIndexRoute,
  AppAsseteIndexLazyRoute: AppAsseteIndexLazyRoute,
  AppLawyerWorkbenchIndexLazyRoute: AppLawyerWorkbenchIndexLazyRoute,
  AppNodeOperatorIndexLazyRoute: AppNodeOperatorIndexLazyRoute,
  AppAsseteInfoIdLazyRoute: AppAsseteInfoIdLazyRoute,
  AppEvaluationInfoIdLazyRoute: AppEvaluationInfoIdLazyRoute,
  AppLawyerWorkbenchInitialReviewIdLazyRoute:
    AppLawyerWorkbenchInitialReviewIdLazyRoute,
  AppLawyerWorkbenchOfflineExecutionIdLazyRoute:
    AppLawyerWorkbenchOfflineExecutionIdLazyRoute,
  AppEvaluationReportManagementIndexRoute:
    AppEvaluationReportManagementIndexRoute,
  AppAsseteAddAsseteIndexLazyRoute: AppAsseteAddAsseteIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexLazyRoute
  '/evaluation': typeof AppEvaluationIndexRoute
  '/assete': typeof AppAsseteIndexLazyRoute
  '/lawyerWorkbench': typeof AppLawyerWorkbenchIndexLazyRoute
  '/nodeOperator': typeof AppNodeOperatorIndexLazyRoute
  '/assete/info/$id': typeof AppAsseteInfoIdLazyRoute
  '/evaluation/info/$id': typeof AppEvaluationInfoIdLazyRoute
  '/lawyerWorkbench/initialReview/$id': typeof AppLawyerWorkbenchInitialReviewIdLazyRoute
  '/lawyerWorkbench/offlineExecution/$id': typeof AppLawyerWorkbenchOfflineExecutionIdLazyRoute
  '/evaluation/reportManagement': typeof AppEvaluationReportManagementIndexRoute
  '/assete/addAssete': typeof AppAsseteAddAsseteIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexLazyRoute
  '/evaluation': typeof AppEvaluationIndexRoute
  '/assete': typeof AppAsseteIndexLazyRoute
  '/lawyerWorkbench': typeof AppLawyerWorkbenchIndexLazyRoute
  '/nodeOperator': typeof AppNodeOperatorIndexLazyRoute
  '/assete/info/$id': typeof AppAsseteInfoIdLazyRoute
  '/evaluation/info/$id': typeof AppEvaluationInfoIdLazyRoute
  '/lawyerWorkbench/initialReview/$id': typeof AppLawyerWorkbenchInitialReviewIdLazyRoute
  '/lawyerWorkbench/offlineExecution/$id': typeof AppLawyerWorkbenchOfflineExecutionIdLazyRoute
  '/evaluation/reportManagement': typeof AppEvaluationReportManagementIndexRoute
  '/assete/addAssete': typeof AppAsseteAddAsseteIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexLazyRoute
  '/_app/evaluation/': typeof AppEvaluationIndexRoute
  '/_app/assete/': typeof AppAsseteIndexLazyRoute
  '/_app/lawyerWorkbench/': typeof AppLawyerWorkbenchIndexLazyRoute
  '/_app/nodeOperator/': typeof AppNodeOperatorIndexLazyRoute
  '/_app/assete/info/$id': typeof AppAsseteInfoIdLazyRoute
  '/_app/evaluation/info/$id': typeof AppEvaluationInfoIdLazyRoute
  '/_app/lawyerWorkbench/initialReview/$id': typeof AppLawyerWorkbenchInitialReviewIdLazyRoute
  '/_app/lawyerWorkbench/offlineExecution/$id': typeof AppLawyerWorkbenchOfflineExecutionIdLazyRoute
  '/_app/evaluation/reportManagement/': typeof AppEvaluationReportManagementIndexRoute
  '/_app/assete/addAssete/': typeof AppAsseteAddAsseteIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/evaluation'
    | '/assete'
    | '/lawyerWorkbench'
    | '/nodeOperator'
    | '/assete/info/$id'
    | '/evaluation/info/$id'
    | '/lawyerWorkbench/initialReview/$id'
    | '/lawyerWorkbench/offlineExecution/$id'
    | '/evaluation/reportManagement'
    | '/assete/addAssete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluation'
    | '/assete'
    | '/lawyerWorkbench'
    | '/nodeOperator'
    | '/assete/info/$id'
    | '/evaluation/info/$id'
    | '/lawyerWorkbench/initialReview/$id'
    | '/lawyerWorkbench/offlineExecution/$id'
    | '/evaluation/reportManagement'
    | '/assete/addAssete'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/evaluation/'
    | '/_app/assete/'
    | '/_app/lawyerWorkbench/'
    | '/_app/nodeOperator/'
    | '/_app/assete/info/$id'
    | '/_app/evaluation/info/$id'
    | '/_app/lawyerWorkbench/initialReview/$id'
    | '/_app/lawyerWorkbench/offlineExecution/$id'
    | '/_app/evaluation/reportManagement/'
    | '/_app/assete/addAssete/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/evaluation/",
        "/_app/assete/",
        "/_app/lawyerWorkbench/",
        "/_app/nodeOperator/",
        "/_app/assete/info/$id",
        "/_app/evaluation/info/$id",
        "/_app/lawyerWorkbench/initialReview/$id",
        "/_app/lawyerWorkbench/offlineExecution/$id",
        "/_app/evaluation/reportManagement/",
        "/_app/assete/addAssete/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/evaluation/": {
      "filePath": "_app/evaluation/index.tsx",
      "parent": "/_app"
    },
    "/_app/assete/": {
      "filePath": "_app/assete/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/lawyerWorkbench/": {
      "filePath": "_app/lawyerWorkbench/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/nodeOperator/": {
      "filePath": "_app/nodeOperator/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/assete/info/$id": {
      "filePath": "_app/assete/info/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/evaluation/info/$id": {
      "filePath": "_app/evaluation/info/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/lawyerWorkbench/initialReview/$id": {
      "filePath": "_app/lawyerWorkbench/initialReview/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/lawyerWorkbench/offlineExecution/$id": {
      "filePath": "_app/lawyerWorkbench/offlineExecution/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/evaluation/reportManagement/": {
      "filePath": "_app/evaluation/reportManagement/index.tsx",
      "parent": "/_app"
    },
    "/_app/assete/addAssete/": {
      "filePath": "_app/assete/addAssete/index.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
