/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppAsseteIndexImport } from './routes/_app/assete/index'
import { Route as AppAsseteAddAsseteIndexImport } from './routes/_app/assete/addAssete/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppAsseteIndexRoute = AppAsseteIndexImport.update({
  id: '/assete/',
  path: '/assete/',
  getParentRoute: () => AppRoute,
} as any)

const AppAsseteAddAsseteIndexRoute = AppAsseteAddAsseteIndexImport.update({
  id: '/assete/addAssete/',
  path: '/assete/addAssete/',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/': {
      id: '/_app/assete/'
      path: '/assete'
      fullPath: '/assete'
      preLoaderRoute: typeof AppAsseteIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/addAssete/': {
      id: '/_app/assete/addAssete/'
      path: '/assete/addAssete'
      fullPath: '/assete/addAssete'
      preLoaderRoute: typeof AppAsseteAddAsseteIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAsseteIndexRoute: typeof AppAsseteIndexRoute
  AppAsseteAddAsseteIndexRoute: typeof AppAsseteAddAsseteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAsseteIndexRoute: AppAsseteIndexRoute,
  AppAsseteAddAsseteIndexRoute: AppAsseteAddAsseteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexRoute
  '/assete': typeof AppAsseteIndexRoute
  '/assete/addAssete': typeof AppAsseteAddAsseteIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/assete': typeof AppAsseteIndexRoute
  '/assete/addAssete': typeof AppAsseteAddAsseteIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/assete/': typeof AppAsseteIndexRoute
  '/_app/assete/addAssete/': typeof AppAsseteAddAsseteIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/assete' | '/assete/addAssete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assete' | '/assete/addAssete'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/assete/'
    | '/_app/assete/addAssete/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/assete/",
        "/_app/assete/addAssete/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/assete/": {
      "filePath": "_app/assete/index.tsx",
      "parent": "/_app"
    },
    "/_app/assete/addAssete/": {
      "filePath": "_app/assete/addAssete/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
