/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'

// Create Virtual Routes

const AppIndexLazyImport = createFileRoute('/_app/')()
const AppAsseteIndexLazyImport = createFileRoute('/_app/assete/')()
const AppAsseteAddAsseteIndexLazyImport = createFileRoute(
  '/_app/assete/addAssete/',
)()
const AppAsseteInfoIdLazyImport = createFileRoute('/_app/assete/info/$id')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))

const AppAsseteIndexLazyRoute = AppAsseteIndexLazyImport.update({
  id: '/assete/',
  path: '/assete/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/assete/index.lazy').then((d) => d.Route),
)

const AppAsseteAddAsseteIndexLazyRoute =
  AppAsseteAddAsseteIndexLazyImport.update({
    id: '/assete/addAssete/',
    path: '/assete/addAssete/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/assete/addAssete/index.lazy').then((d) => d.Route),
  )

const AppAsseteInfoIdLazyRoute = AppAsseteInfoIdLazyImport.update({
  id: '/assete/info/$id',
  path: '/assete/info/$id',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/assete/info/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/': {
      id: '/_app/assete/'
      path: '/assete'
      fullPath: '/assete'
      preLoaderRoute: typeof AppAsseteIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/info/$id': {
      id: '/_app/assete/info/$id'
      path: '/assete/info/$id'
      fullPath: '/assete/info/$id'
      preLoaderRoute: typeof AppAsseteInfoIdLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/assete/addAssete/': {
      id: '/_app/assete/addAssete/'
      path: '/assete/addAssete'
      fullPath: '/assete/addAssete'
      preLoaderRoute: typeof AppAsseteAddAsseteIndexLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppAsseteIndexLazyRoute: typeof AppAsseteIndexLazyRoute
  AppAsseteInfoIdLazyRoute: typeof AppAsseteInfoIdLazyRoute
  AppAsseteAddAsseteIndexLazyRoute: typeof AppAsseteAddAsseteIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppAsseteIndexLazyRoute: AppAsseteIndexLazyRoute,
  AppAsseteInfoIdLazyRoute: AppAsseteInfoIdLazyRoute,
  AppAsseteAddAsseteIndexLazyRoute: AppAsseteAddAsseteIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexLazyRoute
  '/assete': typeof AppAsseteIndexLazyRoute
  '/assete/info/$id': typeof AppAsseteInfoIdLazyRoute
  '/assete/addAssete': typeof AppAsseteAddAsseteIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexLazyRoute
  '/assete': typeof AppAsseteIndexLazyRoute
  '/assete/info/$id': typeof AppAsseteInfoIdLazyRoute
  '/assete/addAssete': typeof AppAsseteAddAsseteIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexLazyRoute
  '/_app/assete/': typeof AppAsseteIndexLazyRoute
  '/_app/assete/info/$id': typeof AppAsseteInfoIdLazyRoute
  '/_app/assete/addAssete/': typeof AppAsseteAddAsseteIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/assete' | '/assete/info/$id' | '/assete/addAssete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assete' | '/assete/info/$id' | '/assete/addAssete'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/assete/'
    | '/_app/assete/info/$id'
    | '/_app/assete/addAssete/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/assete/",
        "/_app/assete/info/$id",
        "/_app/assete/addAssete/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/assete/": {
      "filePath": "_app/assete/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/assete/info/$id": {
      "filePath": "_app/assete/info/$id.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/assete/addAssete/": {
      "filePath": "_app/assete/addAssete/index.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
